In [1]:
## requirement library 
import pandas as pd
import numpy as np

In [2]:
## Load dataset 
data=pd.read_csv("C:\\Users\\Madhav Yadav\\OneDrive\\Desktop\\Medical_Operations_Intelligence_Dashboard\\data\\fact_outbreak.csv")

In [3]:
## Show first 5 row 
data.head()

,outbreak_id,date_id,state_id,disease_id,source_id,new_outbreak_flag,controlled_flag,containment_rate_pct,response_time_hours,alert_level,predicted_cases,historical_cases,forecast_accuracy_pct,hospital_readiness_score,resource_readiness_score,emergency_alert_flag,state_name_raw
0,1,6,3,6,6,YES,Yes,100.0,55.2,High,42,44,97.8,62.4,71.6,False,Assam
1,2,28,32,4,3,YES,Yes,93.5,38.9,Moderate,2772,3768,74.5,99.0,75.9,0,Puducherry
2,3,8,20,3,4,Y,TRUE,100.0,80.9,Moderate,4406,3434,71.4,67.1,62.8,False,Punjab
3,4,23,2,12,4,Y,TRUE,82.9,49.0,Moderate,3024,3885,80.7,70.1,55.7,False,Arunachal Pradesh
4,5,7,32,8,5,True,YES,100.0,73.2,High,1232,1013,75.1,51.0,71.6,N,Puducherry

In [4]:
data.describe(include='all')

,outbreak_id,date_id,state_id,disease_id,source_id,new_outbreak_flag,controlled_flag,containment_rate_pct,response_time_hours,alert_level,predicted_cases,historical_cases,forecast_accuracy_pct,hospital_readiness_score,resource_readiness_score,emergency_alert_flag,state_name_raw
count,2530.000000,2530.000000,2530.000000,2530.000000,2530.000000,2530,2530,2430.000000,2430.000000,2530,2530.000000,2530.000000,2428.000000,2430.000000,2530.000000,2530,2530
unique,NaN,NaN,NaN,NaN,NaN,7,14,NaN,NaN,12,NaN,NaN,NaN,NaN,NaN,14,99
top,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,Low,NaN,NaN,NaN,NaN,NaN,no,Tamil Nadu
freq,NaN,NaN,NaN,NaN,NaN,373,279,NaN,NaN,1228,NaN,NaN,NaN,NaN,NaN,344,92
mean,1250.079051,18.426877,17.003162,6.462055,3.547431,NaN,NaN,64.504938,52.473432,NaN,2644.646245,2513.854941,81.791392,70.122140,67.643913,NaN,NaN
std,721.103523,10.491876,9.196548,3.444003,1.664745,NaN,NaN,19.203297,43.621137,NaN,1615.958199,1428.245163,11.174669,14.695583,17.470749,NaN,NaN
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,6.900000,2.000000,NaN,18.000000,20.000000,55.600000,18.900000,3.000000,NaN,NaN
25%,627.250000,9.000000,9.000000,3.000000,2.000000,NaN,NaN,51.025000,25.400000,NaN,1331.250000,1307.750000,73.200000,60.325000,55.900000,NaN,NaN
50%,1248.500000,18.000000,17.000000,6.000000,4.000000,NaN,NaN,64.400000,50.650000,NaN,2525.000000,2479.000000,82.000000,70.550000,68.000000,NaN,NaN
75%,1873.750000,28.000000,25.000000,9.000000,5.000000,NaN,NaN,78.100000,74.375000,NaN,3756.000000,3723.750000,91.000000,80.500000,79.700000,NaN,NaN
max,2500.000000,36.000000,32.000000,12.000000,6.000000,NaN,NaN,100.000000,483.502571,NaN,6841.000000,4997.000000,100.000000,100.000000,100.000000,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2530 entries, 0 to 2529
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   outbreak_id               2530 non-null   int64
 1   date_id                   2530 non-null   int64
 2   state_id                  2530 non-null   int64
 3   disease_id                2530 non-null   int64
 4   source_id                 2530 non-null   int64
 5   new_outbreak_flag         2530 non-null   object
 6   controlled_flag           2530 non-null   object
 7   containment_rate_pct      2430 non-null   float64
 8   response_time_hours       2430 non-null   float64
 9   alert_level               2530 non-null   object
 10  predicted_cases           2530 non-null   int64
 11  historical_cases          2530 non-null   int64
 12  forecast_accuracy_pct     2428 non-null   float64
 13  hospital_readiness_score  2430 non-null   float64
 14  resource_readiness_score  2530 non-null   float64
 15  emergency_alert_flag      2530 non-null   object
 16  state_name_raw            2530 non-null   object
dtypes: float64(5), int64(7), object(5)
memory usage: 336.1+ KB

In [6]:
## seperate columns with the numerical and categorical 
num=[]
cat=[]
for i in data.columns:
    if data[i].dtype=='int64' or data[i].dtype=='float64':
        num.append(i)
    else:
        cat.append(i)
print('Numerical Columns :',num)
print("Categorical Columns :",cat)

Numerical Columns : ['outbreak_id', 'date_id', 'state_id', 'disease_id', 'source_id', 'containment_rate_pct', 'response_time_hours', 'predicted_cases', 'historical_cases', 'forecast_accuracy_pct', 'hospital_readiness_score', 'resource_readiness_score']
Categorical Columns : ['new_outbreak_flag', 'controlled_flag', 'alert_level', 'emergency_alert_flag', 'state_name_raw']

In [7]:
# checking the value count of the categorical columns 
for i in cat:
    print(data[i].value_counts())

new_outbreak_flag
True    373
Y       370
Yes     370
YES     361
yes     359
TRUE    351
1       346
Name: count, dtype: int64
controlled_flag
True     279
TRUE     278
yes      275
Y        256
Yes      247
YES      239
1        225
N        120
0        115
No       110
FALSE    106
False     99
no        99
NO        82
Name: count, dtype: int64
alert_level
Low           1228
Moderate       847
High           328
LOW             24
 Low            21
low             19
MODERATE        17
moderate        15
 Moderate       11
 High            8
high             6
HIGH             6
Name: count, dtype: int64
emergency_alert_flag
no       344
NO       342
False    341
FALSE    333
No       325
N        324
0        321
True      33
Y         32
YES       32
Yes       29
TRUE      29
1         25
yes       20
Name: count, dtype: int64
state_name_raw
Tamil Nadu          92
Punjab              90
Puducherry          89
Uttarakhand         86
Mizoram             85
                    ..
LADAKH               1
 Assam               1
HIMACHAL PRADESH     1
ODISHA               1
 Odisha              1
Name: count, Length: 99, dtype: int64

In [133]:
data['new_outbreak_flag'].value_counts()

new_outbreak_flag
True    373
Y       370
Yes     370
YES     361
yes     359
TRUE    351
1       346
Name: count, dtype: int64

In [134]:
count = 0
for i in range(len(data['controlled_flag'])):
    if data['controlled_flag'][i]=='TRUE':
        count += 1
print(count)

278

In [136]:
# cleaning column : new_outbreak_flag
print(data['new_outbreak_flag'].value_counts())
data['new_outbreak_flag'] = data['new_outbreak_flag'].replace(['True','Y','Yes','YES','yes','1'], 'True',inplace=True)
data['new_outbreak_flag'] = data['new_outbreak_flag'].replace(['False','N','No','NO','0'], 'False',inplace=True)
print("After cleaning")
print(data['new_outbreak_flag'].value_counts())

new_outbreak_flag
True    2179
TRUE     351
Name: count, dtype: int64
After cleaning
new_outbreak_flag
True    2179
TRUE     351
Name: count, dtype: int64

C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\461036771.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['new_outbreak_flag'] = data['new_outbreak_flag'].replace(['True','Y','Yes','YES','yes','1'], 'True',inplace=True)
C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\461036771.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['new_outbreak_flag'] = data['new_outbreak_flag'].replace(['False','N','No','NO','0'], 'False',inplace=True)

In [116]:
## Cleaning for this column : controlled_flag 

print("Before cleaning ")
print(data['controlled_flag'].value_counts())
data['controlled_flag']=data['controlled_flag'].replace(['True','TRUE','Yes','Y','1',1,'YES','yes',],True,inplace=True)
data['controlled_flag']=data['controlled_flag'].replace(['False','FALSE','no','N','No','NO',0,'0'],False,inplace=True)
print("After cleaning ")
data['controlled_flag'].value_counts()

Before cleaning
controlled_flag
True     1799
False     731
Name: count, dtype: int64
After cleaning

C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\2549753257.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['controlled_flag']=data['controlled_flag'].replace(['True','TRUE','Yes','Y','1',1,'YES','yes',],True,inplace=True)
C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\2549753257.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['controlled_flag']=data['controlled_flag'].replace(['False','FALSE','no','N','No','NO',0,'0'],False,inplace=True)

controlled_flag
True     1799
False     731
Name: count, dtype: int64

In [117]:
data.head()

,outbreak_id,date_id,state_id,disease_id,source_id,new_outbreak_flag,controlled_flag,containment_rate_pct,response_time_hours,alert_level,predicted_cases,historical_cases,forecast_accuracy_pct,hospital_readiness_score,resource_readiness_score,emergency_alert_flag,state_name_raw
0,1,6,3,6,6,True,True,100.0,55.2,High,42,44,97.8,62.4,71.6,False,Assam
1,2,28,32,4,3,True,True,93.5,38.9,Moderate,2772,3768,74.5,99.0,75.9,0,Puducherry
2,3,8,20,3,4,True,True,100.0,80.9,Moderate,4406,3434,71.4,67.1,62.8,False,Punjab
3,4,23,2,12,4,True,True,82.9,49.0,Moderate,3024,3885,80.7,70.1,55.7,False,Arunachal Pradesh
4,5,7,32,8,5,True,True,100.0,73.2,High,1232,1013,75.1,51.0,71.6,N,Puducherry

In [118]:
data['alert_level'].value_counts()

alert_level
Low         1292
Moderate     890
High         348
Name: count, dtype: int64

In [119]:
data['alert_level']=data['alert_level'].str.strip()  # Remove extra space in categories 

data['alert_level']=data['alert_level'].replace(['Low','LOW','low',' Low','low' '  Low'],'Low',inplace=True)
data['alert_level']=data['alert_level'].replace(['High',' High','high','HIGH','  High'],'High',inplace=True)
data['alert_level']=data['alert_level'].replace(['Moderate','MODERATE','moderate',' Moderate','  Moderate'],'Moderate',inplace=True)

C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\994777602.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['alert_level']=data['alert_level'].replace(['Low','LOW','low',' Low','low' '  Low'],'Low',inplace=True)
C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\994777602.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['alert_level']=data['alert_level'].replace(['High',' High','high','HIGH','  High'],'High',inplace=True)
C:\Users\Madhav Yadav\AppData\Local\Temp\ipykernel_7540\994777602.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['alert_level']=data['alert_level'].replace(['Moderate','MODERATE','moderate',' Moderate','  Moderate'],'Moderate',inplace=True)

In [120]:
data['alert_level'].value_counts().sum()

np.int64(2530)

In [121]:
data['alert_level']=data['alert_level'].str.strip()

In [122]:
data['alert_level'].value_counts()

alert_level
Low         1292
Moderate     890
High         348
Name: count, dtype: int64

In [123]:
data.head()

,outbreak_id,date_id,state_id,disease_id,source_id,new_outbreak_flag,controlled_flag,containment_rate_pct,response_time_hours,alert_level,predicted_cases,historical_cases,forecast_accuracy_pct,hospital_readiness_score,resource_readiness_score,emergency_alert_flag,state_name_raw
0,1,6,3,6,6,True,True,100.0,55.2,High,42,44,97.8,62.4,71.6,False,Assam
1,2,28,32,4,3,True,True,93.5,38.9,Moderate,2772,3768,74.5,99.0,75.9,0,Puducherry
2,3,8,20,3,4,True,True,100.0,80.9,Moderate,4406,3434,71.4,67.1,62.8,False,Punjab
3,4,23,2,12,4,True,True,82.9,49.0,Moderate,3024,3885,80.7,70.1,55.7,False,Arunachal Pradesh
4,5,7,32,8,5,True,True,100.0,73.2,High,1232,1013,75.1,51.0,71.6,N,Puducherry